
TOP=../..
.include "$(TOP)/mk/os161.config.mk"

# Just add new directories at the end of the line below.
SUBDIRS= example helloworld getpid forkwait forkfork alloc proc execv_test cat append

.include "$(TOP)/mk/os161.subdir.mk"
